# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml


stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  KUBERNETES_CLUSTER: production
  KUBECONFIG_PATH: /root/.kube/config

build-images:
  image: docker:20-dind
  stage: build
  services:
    - docker:20-dind
  script:
    - cd server
    - docker build -t competitive-connections-server .
    - cd ..
    - cd ui
    - docker build -t competitive-connections-ui .
    - cd ..

deploy-kubernetes:
  image: docker:20-dind
  stage: deploy
  services:
    - docker:20-dind
  script:
    - kubectl create -f k8s/

# E2E Test Job
e2e-test-job:
  stage: test
  script:
    - echo "Running end-to-end tests... This will take about 120 seconds."
    - sleep 5
    - echo "E2E tests completed successfully."


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
